FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# SX (v1.0)

SX API gives support for SX project within Corbel.

# Organization [/v1.0/resource/sx:Organization/{projectId}]

## Create [PUT]

+ Request (application/json)

        {
            "name": "Organization Name",
            "certificates" : [
                {
                    "name": "Name",
                    "certificate": "certficate",
                    "key": "key"
                }
            ]
        }

+ Response 204 (application/json)

## Delete [DELETE]

+ Response 204

# Project [/v1.0/resource/sx:Project]

## Create [POST]

+ Request (application/json)

        {
            "name": "name",
            "organization": "Organization Name",
            "description": "description",
            "services": [
                {
                    "name": "name",
                    "type": "type",
                    "scalable": true,
                    "version": "v0.01",
                    "description": "This is a description.",
                    "group": "group",
                    "dependencies": ["dependency1", "dependency2"],
                    "ports": [
                        {
                            "port": 65535,
                            "url": "http://asdklfjasklfjasasjdflkasjree.com",
                            "certificate": "certificate"
                        }
                    ],
                    "healthchecks": [
                        {
                            "path": "/path/to/something",
                            "protocol": "tcp",
                            "port": 60000,
                            "gracePeriod": 5,
                            "interval": 10,
                            "timeout": 15,
                            "maxConsecutiveFailures": 3
                        }
                    ]
                }
            ]
        }

+ Response 201

    + Headers

            Location: /v1.0/resource/sx:Project/projectId

## Project [/{projectId}]

### Update [PUT]

+ Request (application/json)

        {
            "description": "New description."
        }

+ Response 204

### Delete [DELETE]

+ Response 204

# Environment [/v1.0/resource/sx:Environment]

## Create [POST]

+ Request (application/json)

        {
            "name": "Environment name",
            "project": "Project name",
            "deploySnapshots": true,
            "ttl": 3,
            "serviceConfiguration": [
                {
                    "service": "service",
                    "servers": 7,
                    "ram": 256,
                    "cpu": 1440
                }
            ],
            "properties": {
                "property1": "foo",
                "property2": 5
            }
        }

+ Response 201

## Environment [/{environmentId}]

### Modify [PUT]

+ Request (application/json)

        {
            "deploySnapshots": false
        }

+ Response 204
